### ISSUE TITLE
Engines displayed on Fuel Tanks tab instead of Engines

### ISSUE THREAD

**Issue by Chipper02** [NathanKell/ModularFuelSystem#100]
I noticed this with KW Rocketry but also a couple squad engines during more testing.  All KW Rocketry engines, the Squad S3 KS-25.4 "Mammoth", and Squad LFB KR-1x2 "Twin-Boar" are being displayed on the Fuel Tanks tab instead of the Engines tab AFTER real fuels is installed.  Before Real Fuels they are on the correct tabs.  The two squad parts I can understand since they have small tanks built in but the KW engines do not.

All mods were installed via CKAN.  I checked "KW Rocketry" and "Real Fuels" boxes.  I did not check any "suggestions" but let it pull in the dependencies.  

Testing was done on a stock 32-bit KSP install on Win 7 x64.

.ckan file of installed mods:  https://www.dropbox.com/s/4sc45pgyzfdkxn1/kw-rocketry-engines-in-fuel-tanks-tab-modlist.ckan?dl=0

KSP.log here: https://www.dropbox.com/s/np49haxwjdzagiw/KSP.log?dl=0
Output_log.txt here: https://www.dropbox.com/s/lomx475xzmbu21u/output_log.txt?dl=0

Let me know if you need further details.  I'm highly technical but not a coder.  I love what you have done for KSP and want to help in any way I can.

**Comment by Chipper02** [comment]
Note to self, do not open tickets before AM coffee... ./sigh

**Comment by NathanKell** [comment]
Sorry, I got confused I guess and missed this. It's because old parts that are set to category = Propulsion get autosorted by the game into FuelTanks and Engines based on whether they have a ModuleEngines. But RF engines don't, they have ModuleEnginesRF.

**Comment by NathanKell** [comment]
(This is fixed in new addon engines that have the correct category set from the start).

**Comment by SixthFall** [comment]
Might want to recheck this, I'm getting a bunch of the large kw SRB's as well as most of the KW liquid fuel engines displayed in the fueltank tab instead of the engines tab.

**Comment by NathanKell** [comment]
Per the above lines: Old mods (like, say, KW) set engines to the wrong category (Propulsion, a category that no longer exists). The game tries to sort appropriately, but does not know how to deal with mods which change engine modules. Please ask the part mod author to place their parts in the correct category (i.e. update for the past year of KSP releases.)
