### ISSUE TITLE
LR89 won't ignite: "insufficient resources"

### ISSUE THREAD

**Issue by Schnobs** [NathanKell/ModularFuelSystem#101]
Test case: put any vessel with a LR89 engine on the pad and try to launch.

Comparing their stats in RO_FASA_Atlas.cfg, I find barely any difference in their IGNITOR_RESOURCEs: one requires 0.5 electricity, the other 0.50, but that trailing zero is not the problem -- I tried.

**Comment by NathanKell** [comment]
Fixed in latest RO release (due to stupidity when cloning). Also, an issue with Part.RequestResource is worked around in 1b564fdc72204390f74b9dbebec08e22cc185af2
