### ISSUE TITLE
vapor in fuel lines

### ISSUE THREAD

**Issue by Schnobs** [NathanKell/ModularFuelSystem#102]
This has been giving me a hard time: engines fail to ignite, or ignite and immediately shut down, even though the fuel is supposedly "very stable".

After some messing around, I suspect that the status display isn't too reliable. In all situations where this bit me, the ship was under no or negative acceleration, so it's reasonable to assume that the fuel wouldn't be where it's supposed to be. Doing the right thing, using either high-pressurized tanks or ullage, solved the issue of engines not igniting.

So the problem seems to be that propellant is reported to be "very stable" in situations when it isn't.

**Comment by Librazy** [comment]
A ”very stable“ propellantStatus means propellantStability==1,they are synced all the time.
but it need a Math.Pow(propellantStability, RFSettings.Instance.stabilityPower),that suggested a wrong RFSettings.Instance.stabilityPower maybe used in your KSP

**Comment by Librazy** [comment]
Dunno why now when I realized 1^x === 1 ^

**Comment by Schnobs** [comment]
To clarify: After the previous stage burns out, it takes some time (two seconds or maybe five) until the fuel is reported as anything less than very stable. However, no matter how quickly I ignite the next engine, even if at the same time as the decoupler: it immediately shuts down because of vapor in fuel lines.

I'm now using throttled separation motors to provide a few moments of thrust while staging; this way the next stage will ignite and stay lit.

**Comment by NathanKell** [comment]
This should be fixed in the current release. Please let me know if it's not. Sorry I forgot to update this issue...

**Comment by WayneInfinity0526** [comment]
it means fuel floating in fuel tank
