### ISSUE TITLE
RF / Procedural Parts SRBs get wrong configuration on craft reload

### ISSUE THREAD

**Issue by la-magra** [NathanKell/ModularFuelSystem#103]
#### Description

I have encountered this bug which happens every time I reload a craft in which the procedural part SRB has a lowered propellant level.
On craft reload (save/load, or scene change) the SRB has a increased burntime (i.e. a smaller exhaust).
#### Steps to reproduce
1. Have Procedural Parts and Real Fuels
2. Open the VAB, create craft with pod and procedural real fuels SRB
3. Lower SRB propellant level.
4. Save / Load same craft.
5. SRB should have increased burntime.

[ckan](https://drive.google.com/file/d/0B1ej-t23Fh31U2tONXllN0plVzA/view?usp=sharing)
[log](https://drive.google.com/file/d/0B1ej-t23Fh31LS1sTy1SR0V3eXc/view?usp=sharing)
[MMconfigCache](https://drive.google.com/file/d/0B1ej-t23Fh31TzZKY0w1MUwtb28/view?usp=sharing)

ps. I'm not sure if this is more of a bug of Real Fuels or Procedural Parts... If you think it's needed I'll submit the same report to PP.

**Comment by Starwaster** [comment]
Almost two years later, I'm thinking that this is more of a problem with Procedural SRB, which I've currently taken under my wing and that code definitely has issues, including with calculating thrust and burn time. (in fact, the whole thing is a little ass backwards with how an SRB should work. I've been looking into it but it's had to take a bit of a backseat to the bell issue. I'm going to go ahead and close this and... I think a related issue might already be created for PP, if not I'll make one.
