### ISSUE TITLE
Engines with both ModuleRCSFX and ModuleEnginesRF don't play nice

### ISSUE THREAD

**Issue by ntwest** [NathanKell/ModularFuelSystem#105]
There's something screwy with how the ModuleRCSFX and ModuleEngineRF are interacting.

When I have an engine that has both sets of modules (for example, the SpaceY orbital manuvering systems, which include throttable thrusters and RCS), sometimes after editing the engine settings the RCS settings don't respond - clicking the button fails to change the fuel. Clicking the *second* "Show GUI" Button opens the configure window, but I can't select other fuel types, nor change the Tech Level.

However, If I select the *first* Show GUI Button, then select the *second* Show GUI Button, and finally Hide the first Show GUI button, I can then configure the RCS Thrusters. It's like there's something in the GUI for these components that gets confused.

To reproduce the issue, create an engine with a ModuleRCSFX module, a ModuleEngineConfigs of type = ModuleRCSFX and a  ModuleEngineConfigs of type = ModuleEnginesRF.

There may be a larger issue around the fact that we end up with two "ModuleEngineConfigs" in the persistent save file but the "type" is not persisted? How does the mod know which ModuleEngineConfigs modifies the RCS module and which modifies the engine module?

Also, even after doing my workaround, I have found that it seems that it doesn't apply symmetry properly to the RCS engines - Only the one engine actually gets the right fuel for the RCS thrusters. A simple remove / re-add fixed that.

**Comment by stratochief66** [comment]
@NathanKell (?)

ModuleRCSFX no longer exists, right. This issue can probably be closed.

**Comment by NathanKell** [comment]
Correct, not valid for 1.0.5. @ntwest if you still experience issues in 1.0.5 let us know.
