### ISSUE TITLE
Tweakscaled engines doesn't scale thrust in flight

### ISSUE THREAD

**Issue by 01010101lzy** [NathanKell/ModularFuelSystem#106]
Win10 64bit, KSP 1.0.4 64bit with RF v10.2(need to be checked again, see comment below)(seems that x32 also has the problem)
steps to recreate the issue:
1 remove the Tweakscale module remover(if any) in RF folder. Install Tweakscale.
2 pick an engine(for example, one with 100kN thrust), add to the craft. Tweakscale it.
3 check the RF GUI. Everything looks fine(thrust becomes 800kN). MechJeb also seems fine for TWR.
4 Launch. Engine's thrust come back to the orignal one.(in this example, 100kN)

**Comment by Starwaster** [comment]
First: what is the current status of this problem? Can it still be confirmed to be an issue with the latest versions of Real Fuels + Tweakscale?

Second: *Can it be reproduced in the 32 bit version of KSP?* If the answer to that is 'no' then it's unlikely to get attention. (Linux 64bit is not an issue for support)
