### ISSUE TITLE
TweakScale`d Launch abort system when RF is installed => Crash.

### ISSUE THREAD

**Issue by LebedevRI** [NathanKell/ModularFuelSystem#107]
Hello.
I've had this issue for some time, and i finally know the minimal list of mods needed to reproduce it.
(Debian sid, KSP.x86_64)

Steps to reproduce:
1. Clean KSP install.
2. Using CKAN, install:
2.1. TweakScale
2.2. Real Fuels: Stockalike RF Configs
3. Start KSP
4. Start New (i used sandbox mode)
5. Place new stock `Mk1 Command Pod`
6. Mount new stock `Launch Escape System` on top of `Mk1 Command Pod`
7. Save ship.
8. Load it => all fine.
9. Rescale that `Launch Escape System` one stop down
10. Save ship.
11. Load it => KSP freezes and quits.

Not sure it's RF issue, but If RF is not installed, all works fine, so this looked like the best place...

**Comment by Starwaster** [comment]
what is the status of this problem? Can it still be  confirmed to be an issue with the latest versions of Real Fuels + Tweakscale?

**Comment by Bornholio** [comment]
don't think so tried it with 1.3.1 version
