### ISSUE TITLE
1.7.0.2 throwing exception on KSP load - possible typo

### ISSUE THREAD

**Issue by ABZB** [NathanKell/ModularFuelSystem#115]
Freezing up on "
MissingMethodException: Method not found: 'PhysicsGlobals.get_SkinInteralConductionFactor'.
"                                                                                                                     ^
                                                            
the variable I think it is trying to find is "SkinInternalConductionFactor"
                                                                           ^

**Comment by Starwaster** [comment]
The spelling changed in 1.0.5
