### ISSUE TITLE
engine internals don't honor the "Ignore Max Temperature" cheat

### ISSUE THREAD

**Issue by Schnobs** [NathanKell/ModularFuelSystem#118]
So I had some combination of parts that would instantly overheat. Your classic KSP 1.0.4 heat bug.
No problem, I think, that's what "ignore max temperature" is there for.

This works, until the heat spreads to the engines. Then the engine internals overheat and go boom.

I know that 1.0.5 supposedly solves all heat issues. I'd still suggest that mods should honor the heat cheat.

**Comment by NathanKell** [comment]
@blowfishpro we do this in Solver, right, not in RF?

**Comment by blowfishpro** [comment]
Yes, but engine internal temperature shouldn't be affected by anything but the engine itself.  We should probably add a toggle so that it the "ignore max temp" cheat is enabled it will not explode, but there's no reason why heat from other parts would cause the engine internals to overheat.

**Comment by NathanKell** [comment]
Except the chamber temp does do a temp = max(expected temp, part temp) so if part temp > chamber max (say, part temp is 3900 K) then the chamber temp will go to 3900 K and the engine will slag.

**Comment by blowfishpro** [comment]
Should be fixed in solver now
