### ISSUE TITLE
Propellant stability when Firing Engines.

### ISSUE THREAD

**Issue by kiwivogel** [NathanKell/ModularFuelSystem#122]
Hello, not so much an issue as a suggestion. Now that squad has put a UI framework for showing us when it's safe to stage our parachutes would it be possible to put something similar in place for engine propellant stability? That would be seriously helpful. (I have no idea if squad uses assets for changing the colour of the parachute icon of if it's a simple palet change but it seems this would be easy to implement.) Thanks!

**Comment by NathanKell** [comment]
It's just code, and happily I was the one who added it to the parachute anyway (following Claw's stockbugfixes version). Sounds good, will do when I have a sec.
