### ISSUE TITLE
Hydrogen isostates

### ISSUE THREAD

**Issue by stratochief66** [NathanKell/ModularFuelSystem#125]
TIL:

page 107 of Ignition!, apparently cooling hydrogen also has to change between ortho and para states, which emits 1.5x again as much energy to drop to the lower energy version. I need to find a source about how this progresses as liquid hydrogen heats up and boils off.

Effectively as liquid hydrogen is cooled to a liquid it goes through an additional transition that emits heat. As hydrogen is heated, this transition would occur in reverse, absorbing heat energy just like vapourizing hydrogen does. Very cool.

https://en.wikipedia.org/wiki/Spin_isomers_of_hydrogen

**Comment by Starwaster** [comment]
ok, but what issue does this pose to RF though?

**Comment by stratochief66** [comment]
Not only does hydrogen have a heat capacity, but appreciable heat energy is emitted or consumed in changing the isostate as it is heated or cooled. I created this issue as a reminder for me to look into calculating/finding the how much the equilibrium isostate shifts with temperature in the regularly used liquid hydrogen temperature range (17K - 25K) to actually state the impact this will have on RF.

**Comment by Schnobs** [comment]
No effects we need to deal with.

It is a problem when making liquid hydrogen. Freshly liquefied hydrogen will give off considerable extra heat as it slowly enters para state. This would require a lot of extra cooling during the first weeks of storage.

Instead, a catalyst is used (don't ask me how a catalyst acts on spin) to speed up the conversion; the idea is to convert it ASAP, deal with the excess heat in the liquefaction plant, and only commit it to storage after it has stabilized.

When you vaporize it, the process plays out in reverse. The timeframes are such that you do not need to worry about it in the few moments until you expel it from the nozzle.
