### ISSUE TITLE
Some ModularFuelTanks patch set tank type as Cryogenic but it does not existe for MFT

### ISSUE THREAD

**Issue by sarbian** [NathanKell/ModularFuelSystem#127]
As the title says. 

In those ModularFuelTanks MM patch some tank are set type = Cryogenic but this type is only defined in RealFuel. They should be type = Default

NP2_modularFuelTanks.cfg
SpaceShuttleEngines_modularFuelTanks.cfg
Stretchy.cfg

**Comment by NathanKell** [comment]
@taniwha

**Comment by Starwaster** [comment]
Fixed by ef5469a
