### ISSUE TITLE
Feature request: Display costs

### ISSUE THREAD

**Issue by glilienthal** [NathanKell/ModularFuelSystem#128]
It is very difficult to control the costs of tanks and their contents. 

A number for the total cost of the tank in the editor view (like for the procedural fairings) would be awesome.

**Comment by NathanKell** [comment]
I believe that it states the cost on the GUI window (action group editor mode->click on part, or right-click>Show GUI).

**Comment by glilienthal** [comment]
When I go on a procedural tank and click on "Show UI" I see the possible contents, but no price. So I think that is not working. - Or did I get anything wrong? 

Also, Ideally you'd see the price change every time you resize. (As you do for the procedural fairings.)

**Comment by glilienthal** [comment]
Actually, I now see that there are costs for the tank in full and dry shown. However, for me they are always displayed as zero. (Just updated to the newest version of RO).

**Comment by NathanKell** [comment]
The code is there, it just got removed from the GUI at some point. Huh.
