### ISSUE TITLE
Cavea-B monoprop should use a tiny amount of UMDH every time it ignites.

### ISSUE THREAD

**Issue by kiwivogel** [NathanKell/ModularFuelSystem#130]
I've been doing some digging with respect to Cavea-B. The only proper source seems to be 'Ignition!' (chapter on monopropellants)  the ignition of Cavea-B is apparently rather tricky and requires either a UMDH slug as an ignition source or some device with exposed lithium hydride. While I realize implementing either would pretty much render Cavea-B useless as an RCS fuel it would increase the realism (it would fit the trend of adding finnicky stuff like the HTP for the R-7's). Besides it would still be usable for generic 0.5/1/2 kN thrusters. Something to implement y/n?

**Comment by NathanKell** [comment]
Alas I don't know how to do it for RCS at this point (though when I combine RCS and Engine at some future time it gets easier) and I'd really rather not have it for engines but not RCS.
Also, this goes on the RO repo. ;)

**Comment by NathanKell** [comment]
(great find though!)
