### ISSUE TITLE
Odd right click GUI behaviour in VAB

### ISSUE THREAD

**Issue by stratochief66** [NathanKell/ModularFuelSystem#140]
Done with a RealFuel compile @NathanKell shared on IRC
1. The autofill fuel button (ie. "100% HTP") starts at the bottom of the right click menu for a crew capsule in the VAB, then seems to quickly climb to the top of the list.
2. Same place, Right click menu of a crewed capsule in the VAB. If I adjust a slider of a resource on that capsule, I get many duplicates of the autofill fuel button. I don't believe all of these try to climb to the top of the list.

**Comment by NZBanana** [comment]
I have also experienced this issue with RF 11.2.0 with KSP 1.1.2.1260(x64) on windows running RP-0 and almost all suggested mods

This is my log:
[output_log.txt](https://github.com/NathanKell/ModularFuelSystem/files/276309/output_log.txt)

Video of the issue:
https://www.youtube.com/watch?edit=vd&v=F9jMX5UlApw
