### ISSUE TITLE
Tac Life Support Auto-Balance

### ISSUE THREAD

**Issue by arsenictonic** [NathanKell/ModularFuelSystem#144]
Add a function that allows autofill with correct portions of food/oxygen/water.

**Comment by Gordon-Dry** [comment]
Oh my ...

I tried to create a generic patch that does this the last days.

I came to the following conclusion:

My patch works by now, but...

When I pre-fill a TANK and then delete the stock !RESOURCE afterwards, the TANK is empty in VAB/SPC.
But in ModuleManager.ConfigCache it's stated clearly:
The TANK is filled.

**Comment by Gordon-Dry** [comment]
I would much appreciate a button in the context menu (VAB/SPH) of any part that is
- crewable
- has ModuleFuelTanks type = ServiceModule
- does not already have prefilled TAC-LS resources*

to autofill the remaining tank volume with TAC-LS resources in a balanced way.

*ofc when all resources are removed than the button should be available again.

That would be much better than trying to create a patch that has to fight with other patches which use FINAL.

**Comment by Bornholio** [comment]
we had a little "engine " part in RP0 dev for a while that did this. placed it, filled tanks then removed it.

**Comment by NathanKell** [comment]
Smart!!

Sent by my thumbs, slowly.

**Comment by glilienthal** [comment]
Could it be added to the MF code so that it seems as if such an engine is always there? 

However it is solved, this feature would be really great!

**Comment by Starwaster** [comment]
While there are no code changes planned that would allow for automatic tank configuration, I would like to point out #218 which has been implemented. Look at the linked issue to see how to configure the part with resources that cannot be emptied by MFS or RF. If you add an UNMANAGED_RESOURCE that quantity will stay there. You can add tanks that contain more of it but the original quantity will always be there even if you later 'Remove All Tanks'

Closing this for now. It has the back burner label so maybe at a future date it might be revisited.

**Comment by siimav** [comment]
Actually Pap already added a *life support engine* into RO that works perfectly for getting the right resource proportions.
https://github.com/KSP-RO/RealismOverhaul/blob/4123530773edaead0b7478ab7b1e978546978425/GameData/RealismOverhaul/RO_RecommendedMods/TACLS/RO_TACLS_FakeEngine.cfg
