### ISSUE TITLE
ModuleEngineConfigs is setting part.mass directly

### ISSUE THREAD

**Issue by shadowmage45** [NathanKell/ModularFuelSystem#146]
See:
https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Engines/ModuleEngineConfigs.cs#L257-L264

And:
https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Engines/ModuleEngineConfigs.cs#L991-L1004

**Comment by NathanKell** [comment]
I think this got handled elsewhere? If not, please poke.

**Comment by shadowmage45** [comment]
I believe the problem still exists, merely the lines in question have moved around a bit:

https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Engines/ModuleEngineConfigs.cs#L273

https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Engines/ModuleEngineConfigs.cs#L1012

Honestly I'm not sure if these effect anything in practice, I haven't tested out RO stuff in quite some time.
