### ISSUE TITLE
RF issue with module engines and fuel tanks

### ISSUE THREAD

**Issue by raidernick** [NathanKell/ModularFuelSystem#150]
@NathanKell asked me to tag you on this @taniwha 

When you have a part that has a module engine and module fuel tank on it, if you remove all tanks the option to refill them with the correct fuel ratios is not there, neither in the right click menu or the separate fuels menu. There is no issue with parts that are just tanks with no engine module on it.

**Comment by Starwaster** [comment]
Can't currently repro this. Not sure when it got fixed but it doesn't look like it's an issue anymore.
