### ISSUE TITLE
Send message to FS Texture Switch on config change

### ISSUE THREAD

**Issue by NathanKell** [NathanKell/ModularFuelSystem#155]
per @asmi84 allow detecting FSTextureSwitch module and sending it a message to set texture when SetConfiguration() runs.

**Comment by Starwaster** [comment]
This sounds like it would need a bit more than that such as stored information as to what to set the texture to. (I presume it would be in the MEC CONFIG)

**Comment by DRVeyl** [comment]
Every part receives a `UpdateUsesdBy` message from MEC in SetConfiguration (git blame puts this at 5+ years old, so maybe NK did this and the issue is still open?):
```
for(int i = parts.Count - 1; i >= 0; --i)
    parts[i].SendMessage("UpdateUsedBy", SendMessageOptions.DontRequireReceiver);
```

I have a PR that adds:
```
    part.SendMessage("OnEngineConfigurationChanged", SendMessageOptions.DontRequireReceiver);
```
So the specific part with the MEC module gets a dedicated event.
