### ISSUE TITLE
TweakScale'd fueltank causing explosion

### ISSUE THREAD

**Issue by Doyle3694** [NathanKell/ModularFuelSystem#159]
This is on 1.2.1 with the 1.2.0 TweakScale and ModularFuelSystem version, along with a ton of other mods, though I had problems with it on 1.2.0 as well but didnt catch them on log. All mods except MechJeb are installed through ckan.

I'm using two TweakScale'd fueltanks, FL-T200 with an FL-T400 on top of it, both scaled to 0.625m. On the top is a Probodobodyne along with a ton of other things and on the bottom is an LV-1 Engine. The setup works fine for the first burn but on the second one it blows up and before it does you can see the bottom fueltank sortof drifting into the top one. Whether it's the fuel going low enough for the center of mass to change to some critical point or it's timewarp messing it up or some third factor, I do not know.

I first posted this on TweakScale but as suggested over there I tried it without ModularFuelSystem, and the same craft from the same point worked fully as intended, so most likely on ModularFuelSystem or a compatibility issue.

[KSP.zip](https://github.com/NathanKell/ModularFuelSystem/files/568008/KSP.zip)
Lines 22988, 35379 (Two different explosions, same craft at same point but with a reload in between)
![ksp](https://cloud.githubusercontent.com/assets/2184532/19952349/e8336716-a164-11e6-9074-0822585ca21d.png)

**Comment by Starwaster** [comment]
Do you know if the mass was negative on either the T200 or T400 tank? (you can check for that by putting down just the tank and then scaling it and look at the Engineer's Report' to see what the mass is)

**Comment by Starwaster** [comment]
Closing this as there's been no response from to request for additional information and no other indication of this being a problem among other players.

**Comment by Doyle3694** [comment]
Sorry for not answering, I seem to have missed the notification from github before. The tanks did indeed have negative mass.

Can't really answer any other inquiry as this install is long gone, so yes a close is probably in order since nobody can reproduce it anymore.
