### ISSUE TITLE
RCS things always show the exhaust effect

### ISSUE THREAD

**Issue by Sifaus** [NathanKell/ModularFuelSystem#163]
As the title. 

I installed the mod with CKAN, which installed Module Manager (2.7.5), Real Fuels Stockalike RF Configs (3.2.1), Solver Engines Plugin (3.0) and Community Resource Pack (0.6.4.0). I have no other mods installed, i reinstalled the game to make sure it is a clean install. It didn't solve the problem, so yeah. I'm using latest KSP.

I restarted multiple times too, that didn't solve it either.

![psdduli](https://cloud.githubusercontent.com/assets/6386917/21391963/71f18544-c796-11e6-8ca6-0f962c5eec28.jpg)

**Comment by blowfishpro** [comment]
I noticed this in my testing, but I think it's an issue in RF Stockalike's RealPlume configs rather than RF's code. @Raptor831 would you happen to have any insight here?  I see a patch in RF Stockalike changing things to `ModuleRCSFX` but I don't see anything changing the effects.

**Comment by Sifaus** [comment]
I didn't have RealPlum installed when i got this error, but just installing RF (which forces an Stockalike RF Configs install) causes this then?

**Comment by blowfishpro** [comment]
Isn't RealPlume listed as a dependency for RF Stockalike?  It might not really matter though, I think the problem is that the effect definitions need to be modified but aren't being

**Comment by Sifaus** [comment]
It isn't. It is RF Stockalike is a dependancy for RF but RF Stockalike doesn't install RealPlume. Problem continued even after i installed RealPlume to check if that solves it (as you said). But I think you already pinpointed the problem, so yeah. 

Should i post this to RealPlume's issue tracker instead of here?

**Comment by blowfishpro** [comment]
I didn't mean to suggest that installing RealPlume would fix it.

Anyway, did some investigation and it looks like it is indeed a configuration issue in RF Stockalike.  Stock now uses `ModuleRCSFX` but RF Stockalike converts it back to `ModuleRCS` without actually changing the effects.  This will definitely cause the observed behavior.  I'll open an issue at RF Stockalike.
