### ISSUE TITLE
Effects for non-active engine configs play briefly when the flight scene is first loaded

### ISSUE THREAD

**Issue by blowfishpro** [NathanKell/ModularFuelSystem#167]
For the first few seconds in the flight scene, before it finishes initializing, effects for the non-active engine config play.

This is most visible in RF Stockalike because they frequently have different plumes for different engine configs.

**Comment by Starwaster** [comment]
@blowfishpro what's the current status of this? I don't think I ever saw it myself. Is it still an ongoing issue? Can you provide repro instructions?

**Comment by blowfishpro** [comment]
I don't think I've seen this in a while.  Probably safe to close.  I'll re-open if I see it again.
