### ISSUE TITLE
Broken TestFlight interoperability

### ISSUE THREAD

**Issue by PhineasFreak** [NathanKell/ModularFuelSystem#169]
The RF interoperability with TF is broken with the latest release of RF and the test version of TF but it seems like it is not a problem with TF itself:

```
[EXC 23:42:19.713] AmbiguousMatchException: Ambiguous matching in method resolution
	System.Reflection.Binder.FindMostDerivedMatch (System.Reflection.MethodBase[] match)
	System.MonoType.GetMethodImpl (System.String name, BindingFlags bindingAttr, System.Reflection.Binder binder, CallingConventions callConvention, System.Type[] types, System.Reflection.ParameterModifier[] modifiers)
	System.Type.GetMethod (System.String name, BindingFlags bindingAttr)
	RealFuels.TestFlightWrapper..cctor ()
	Rethrow as TypeInitializationException: An exception was thrown by the type initializer for RealFuels.TestFlightWrapper
	RealFuels.Tanks.ModuleFuelTanks.UpdateTestFlight ()
	RealFuels.Tanks.ModuleFuelTanks.UpdateTankType (Boolean initializeAmounts)
	RealFuels.Tanks.ModuleFuelTanks.GetInfo ()
	PartLoader.CompilePartInfo (.AvailablePart newPartInfo, .Part part)
	PartLoader+<CompileParts>c__Iterator62.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
```

Occurs as soon as the KSP part config loader reaches a part that uses the ModuleEnginesRF module. Tested with various engine parts, both stock and modded, provided by RO.

* [KSP log file](https://raw.githubusercontent.com/PhineasFreak/DocBin/master/DocBin/log_files/RF_05012017_234521_KSP_log.txt)
* [Output log file](https://raw.githubusercontent.com/PhineasFreak/DocBin/master/DocBin/log_files/RF_05012017_234521_output_log.txt)

**Comment by jwvanderbeck** [comment]
Possible I borked something in the compile of the latest version.  It has been a while since I built it :)

**Comment by blowfishpro** [comment]
Most likely my fault since I changed the way RF accesses TestFlight.  Should be an easy fix.

**Comment by blowfishpro** [comment]
Putting this here so that I remember.  In https://github.com/NathanKell/ModularFuelSystem/blob/d2877fba99c39e24c62ea3cae20996dbb7893c38/Source/Utilities/TestFlightWrapper.cs#L18

need to bind with specific argument types

```
private const Type[] addInteropValueArgTypes = new[] { typeof(Part), typeof(string), typeof(string), typeof(string) };

...

addInteropValue = tfInterface.GetMethod("AddInteropValue", tfBindingFlags, null, addInteropValueArgTypes, null);
```

**Comment by blowfishpro** [comment]
@PhineasFreak could you try this DLL (just replace it in RealFuels).  I believe this will fix the problem, if so I can merge and release the fix.
[RealFuels.zip](https://github.com/NathanKell/ModularFuelSystem/files/689092/RealFuels.zip)

**Comment by PhineasFreak** [comment]
@blowfishpro with the new RF assembly the loading is by the book. Everything is working as expected by both RF and TestFlight.

**Comment by jwvanderbeck** [comment]
Ah yeah that would do it.  The AddInterop method is overloaded so that you can set various data types beyond just string.
