### ISSUE TITLE
No Animation

### ISSUE THREAD

**Issue by MaximalesGaming** [NathanKell/ModularFuelSystem#175]
@blowfishpro Hey I found two new issues with the animation of thrust.

1. The "Hound"-engine of the Mod Modular Rocket Systems doesn't have a thrust animation, only light effect. You can see it in the picture.
![no_burn_animation](https://cloud.githubusercontent.com/assets/17008430/22183889/89ce9b7a-e0c8-11e6-88a9-0321da9f52af.jpg)

2. The "Hypergolic Sevice Propulsion"-engine's animation of thrust is in the spacecraft. You can see it in the other picture.
![animation_in_spacecraft](https://cloud.githubusercontent.com/assets/17008430/22183918/099ff8c6-e0c9-11e6-8581-c8f74759459f.jpg)

I'll watch for other issues.

Greetings from Germany
MaximalesGaming

**Comment by blowfishpro** [comment]
Hi MaximalesGaming,

It looks like you are using RF Stockalike?  In that case, I think it is an issue with RF Stockalike, not RealFuels itself.  As far as engines go, RF doesn't change anything by itself, that is the responsibility of either RF Stockalike or RO (this is a common point of confusion).

RF Stockalike has its own repository, I think you should report the issue over there

https://github.com/Raptor831/RFStockalike

Let me know if you have any more questions.
