### ISSUE TITLE
ISRU in RealFuels {REQ}

### ISSUE THREAD

**Issue by KAmaia** [NathanKell/ModularFuelSystem#179]
I'm not sure what the feasibility of this would be, however, I have started playing RSS/RF/RP and would like to set up a mining base on the moon.  However what's stopping me is the fact that the ISRU does not function to generate any of the real fuels.  Is this a feature you would consider adding to the game?  

Thanks, 
Krystal.

**Comment by stratochief66** [comment]
https://github.com/jbengtson/RealISRU

Some assembly required, you can always help to make it better :)

I'm focusing on Mars myself.
