### ISSUE TITLE
Support for OPT and SpaceY Expanded 

### ISSUE THREAD

**Issue by RazeBerry** [NathanKell/ModularFuelSystem#187]
OPT and SpaceY expanded are not supported in Real Fuel and result the tanks to have very small volume and the mass ratio is not even close to 1:20, is there anyway I can modify the config to support those mods?

**Comment by Starwaster** [comment]
I thought OPT already had support... I'll look into it. If nothing else, the configs that I wrote for the OPT legacy pack can serve as a basis for any new configs that need doing.

**Comment by Starwaster** [comment]
Ok, RF support is THERE, it's just that the tank volume assigned is too low, by a factor of 2.5 at least. (assuming that the stock amounts allocated are reasonable then 2.5 exactly, but I often found for the legacy parts that the amount of resource space allocated was far less than what the visible representation of fuel tanks on the models could actually hold)

I'll bring it up in the OPT thread but if you want to try to fix it on your own installation then you need to do something like:

`@PART[j_4m_crew]:FINAL
{
    @MODULE[ModuleFuelTanks]
    {
        @volume *= 2.5
    }
}`
doing that for each part that has an RF config.

**Comment by RazeBerry** [comment]
@Starwaster Would you mind help me locating the location of the .cfg file for OPT, since it is not under the \Gamedata\RealFuel folder. That is why I thought it was incompatible with Real Fuel. Also, OPT parts under RealFuel have negative mass in game, not sure why it is happening and it is not because of tweakscale.
