### ISSUE TITLE
[ERR] Unable to find tank definition for type "RCSHighEfficiency" reverting.

### ISSUE THREAD

**Issue by khr15714n** [NathanKell/ModularFuelSystem#189]
KSP.log
[                ] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW2mRCSfuel/KW2mRCSfuel'
[ERR 08:06:26.367] Unable to find tank definition for type "RCSHighEfficiency" reverting.

[                ] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW3mRCSfuel/KW3mRCSfuel'
[ERR 08:06:26.431] Unable to find tank definition for type "RCSHighEfficiency" reverting.
--------------
Patched in ModularFuelTanks/KW_modularFuelTanks.cfg at line 124 and 238

@PART[KW2mRCSfuel]
{
	//!RESOURCE[LiquidFuel] {}
	//!RESOURCE[Oxidizer] {}
	//!RESOURCE[MonoPropellant] {}
	//!RESOURCE[XenonGas] {}
	MODULE
	{
		name = ModuleFuelTanks
		volume = 800
		type = RCSHighEfficiency
	}
}

@PART[KW3mRCSfuel]
{
	//!RESOURCE[LiquidFuel] {}
	//!RESOURCE[Oxidizer] {}
	//!RESOURCE[MonoPropellant] {}
	//!RESOURCE[XenonGas] {}
	MODULE
	{
		name = ModuleFuelTanks
		volume = 2700
		type = RCSHighEfficiency
	}
}
--------------
In RealFuels/Readme_RF.txt for version 8.0 on line 356
"*RCS, RCSHighEfficiency, Jet, and Oxy tanks are deprecated."
--------------
I found an old post (June 9, 2014) in forum
http://forum.kerbalspaceprogram.com/index.php?/topic/58236-122-real-fuels-v1210-april-24/&do=findComment&comment=1192794
no duplicated definition
RealFuels is not installed
--------------
http://forum.kerbalspaceprogram.com/index.php?/topic/58235-122-modular-fuel-tanks-v583/
v5.6.0: 
Remove the RCSHighEfficiency tank type (it is now worse than most tanks) leaving only the RCS tank type.
--------------
How do you want it to be handled? Remove both patches completely or replace RCSHighEfficiency by RCS or ...?

**Comment by jwvanderbeck** [comment]
You are referencing posts from both RealFuels and ModularFuelTanks.  Which are you trying to use?

**Comment by khr15714n** [comment]
As I've wrote: RealFuels is not installed
The "old post of 2014" was the only post in forum that mentioned RCSHighEfficiency and NathanKell asked specific to check: no duplicated definition on my side

Here is ModularFuelSystem and I have ModularFuelSystem installed.

**Comment by Starwaster** [comment]
I changed both references to Default in commit 8c8439778b34807f49830e648bfa805935bf0aec.
