### ISSUE TITLE
Make fuel pump module respect symmetry

### ISSUE THREAD

**Issue by blowfishpro** [NathanKell/ModularFuelSystem#190]
Annoying to have to turn it on for every launch clamp

**Comment by glilienthal** [comment]
yes, please.

**Comment by PhineasFreak** [comment]
@blowfishpro Is this also related to the fact that it is not possible to force it be enabled by default via MM? A custom **pump_rate** value applies correctly but the **enablePump** does not.

**Comment by blowfishpro** [comment]
@PhineasFreak that doesn't work because it gets set to false when you enter the editor:

https://github.com/NathanKell/ModularFuelSystem/blob/8c8439778b34807f49830e648bfa805935bf0aec/Source/Pumps/RefuelingPump.cs#L38

**Comment by blowfishpro** [comment]
Not sure why that wouldn't work.  Would have to look into it more.

**Comment by PhineasFreak** [comment]
Would be possible to change that...without breaking anything in the editor scene?

**Comment by blowfishpro** [comment]
Sorry, realized my first comment was incorrect so I deleted it.  The code I referenced only runs in the flight scene.

**Comment by Starwaster** [comment]
Just to confirm, this is implemented now, right? Ok to go ahead and close?

**Comment by blowfishpro** [comment]
Yep, follows symmetry in the editor.  Also enabled by default.
