### ISSUE TITLE
Suggestion: Add the fuel percentages to Engine UI

### ISSUE THREAD

**Issue by Gordon-Dry** [NathanKell/ModularFuelSystem#196]
Sometimes a rocket with different engines  on the stages also got different fuel mixtures.

To find out which is the correct mixture for the actual engine attached to the tank can be a pita - in most cases I have to detach the stage(s) the see the one entry that is left for that engine.
Detaching and re-ataching quirks the staging so I have to rearrange all staging icons again...
I can odc calculate the percentage for my self using the Liters, but that is not user friendly.

So how about just adding the percentages to the Engines UI?

**Comment by Starwaster** [comment]
The tank UI already does what you need. Open the tank UI (NOT the context / PAW menu) and hover the mouse cursor over each mixture ratio. It will tell you what engines use that ratio, including RCS.

**Comment by Gordon-Dry** [comment]
When there is only one default ratio, so nothing else to choose, there is no way to see the ratio.

That also means that only the ratios of other setups than the actual one are possibly shown.

**Comment by Starwaster** [comment]
Naturally.
