### ISSUE TITLE
RealFuels_KethaneTanks.cfg has multiple passes specified

### ISSUE THREAD

**Issue by blowfishpro** [NathanKell/ModularFuelSystem#198]
All of the passes are marked `:FOR[RealFuels]:FOR[zzzRealFuels]`

Which pass are they actually supposed to run in?

**Comment by blowfishpro** [comment]
Ill add that this will likely be an error in the next version of ModuleManager

**Comment by Starwaster** [comment]
I'm going to have to say to with FOR[zzzRealFuels] given that the history has been

1. FOR[RealFuels]
2. FOR[RealFuels]:FINAL
3. FOR[RealFuels]:FOR[zzzRealFuels]

The intent was clearly to change execution phase to FINAL, then changed by you to be FOR[zzzRealFuels]

(though frankly, FOR[RealFuels] should always have been considered to be acceptable as it was unlikely to change unless another mod changed it in a later phase and this was probably one of those situations where we should have allowed that)

**Comment by blowfishpro** [comment]
Ah, didn't remember doing that.

Makes sense, I'm willing to change it back to the original `:FOR[RealRuels]` and if it turns out anything breaks we can adjust it again.
