### ISSUE TITLE
2.2/3.6kN Thruster cost shenanigans for different fuel mixtures

### ISSUE THREAD

**Issue by aw1621107** [NathanKell/ModularFuelSystem#201]
This one is a bit difficult to explain...

If I select the 2.2/3.6kN thruster in the VAB (part RO-2kN-Thruster) in a sandbox save, and open up the RF GUI, I'm presented with several options for fuel mixtures, as well as some buttons to select the tech level. Hovering over the buttons for different fuel mixtures yields a small window showing various stats for the thruster if it were to use those different fuel mixtures. This is normal.

The thing is that the cost change for a fuel value in the pop-up window doesn't match the cost change on the button to select that fuel mixture. Upon selecting the fuel mixture, the tech level for the thruster is forced to TL2, and the cost quoted on the buttons to select different fuel mixtures now matches that in the pop-up window. Even if the tech level is changed again, the cost in the pop-up window remains that for TL2, and if a new fuel mixture is selected the tech level is forced back to 2.

[Here](https://gfycat.com/gifs/detail/AnguishedRaggedLaughingthrush) is a gfycat demonstrating what I mean

**Comment by aw1621107** [comment]
Looks like forcing the tech level to a particular value is intentional? ModuleEngineConfig.engineManagerGUI() calls `SetConfiguration(nName, true)`, where the second parameter indicates whether the tech level should be reset:

https://github.com/NathanKell/ModularFuelSystem/blob/7c90517f14c0c512e095a711bc9a1cb9a919694b/Source/Engines/ModuleEngineConfigs.cs#L1378-L1416

So I guess the question now is "why"? And I guess the problem with the cost in the window not matching the cost on the button remains

**Comment by Starwaster** [comment]
What is the current status of this? Is this still an outstanding issue?

**Comment by NathanKell** [comment]
Some mixtures have minimum tech levels. The forcing is fine. If the
incorrect cost is being shown or applied that's bad.

Sent by my thumbs, slowly.
