### ISSUE TITLE
Engine selection UI has clicking offset issues?

### ISSUE THREAD

**Issue by aw1621107** [NathanKell/ModularFuelSystem#202]
For some reason, sometimes the engine selection GUI starts acting as if clicks are happening a certain offset from where the cursor actually is. I definitely experience this when messing with RCS quads (RCSBlock, RCSBlockQuarter, etc.). Don't remember it happening with "regular" engines, and not sure whether it happens with attitude jets.

Unfortunately, I don't have a consistent way to reproduce this. I'm working on it though. Sometimes I can get through a few runs of KSP without it happening, other times it happens quite frequently.

[Here](https://gfycat.com/gifs/detail/GraveImpracticalGermanshepherd) is a gfycat showing an example of the behavior

**Comment by Starwaster** [comment]
You're in windowed mode. I too experience issues with clicking when in windowed mode. And it's worse in 1.4.1

NOT a MF / RF problem. Stock problem.

**Comment by aw1621107** [comment]
Huh, didn't know it was a windowed mode thing. Guess there isn't much reason to keep this issue open then.
