### ISSUE TITLE
Sounding payload gets filled by pumps

### ISSUE THREAD

**Issue by pianojosh** [NathanKell/ModularFuelSystem#204]
If you de-tank sounding payload (maybe other payloads too, haven't tried yet) and have a launch clamp with a pump, the pump will fill the tank with that payload.

Would it be possible to exclude the payload categories from being fed by launch clamp pumps?

**Comment by NathanKell** [comment]
RP-0 issue, please post there so we don't forget

Sent by my thumbs, slowly.

**Comment by pianojosh** [comment]
Wilco.
