### ISSUE TITLE
New Cryo discussion

### ISSUE THREAD

**Issue by Starwaster** [NathanKell/ModularFuelSystem#207]
This issue is an informational issue to discuss some new cryo features (going live for the final KSP 1.3.1 update and then on to KSP 1.4.*

The two new features are
Multi-Layer Insulation (layered aluminized mylar)
Dewar type tanks: Vacuum bottles.

MLI can be added to tanks at the TANK_DEFINITION level by setting numberOfMLILayers = True and can also be added by players. Currently there are no TANK_DEFINITION types that have this. Cryogenic and Cryogenic Balloon types are candidates but I have not done this at this time. Configured and player added layers are cumulative. MLI increases mass and cost of a tank part.

Dewar bottles can be added to the individual TANK nodes via isDewar = true and I have already done this for cryogenic TANK nodes in the ServiceModule TANK_DEFINITION. _Not player configurable and will require additional GUI work if we want to make that happen._ No change to mass or cost; we can edit the mass and cost for these tanks if needed? 

These two features work in different ways: Cryo has always worked by treating the part temperature as the outer tank surface, including SOFI insulation if it exists and the conduction is calculated based on the tank thickness and conductivity combined with SOFI thickness and conductivity. It actually uses existing conduction. 

MLI actually adjusts the skin-internal conductivity where the skin is treated as the outermost layer of insulation and skin-internal conduction is adjusted using a simplified version of Lockheeds MLI Equation. (simplified modifed). Heat conductivity is adjusted constantly so that skin-internal conduction is approximately the same as it would be IRL. Part-part conductivity also benefits; we assume that conduction pathways such as struts are minimized and insulated.

Dewars force the boiloff code to use an alternate radiation based model. Any configured TANK insulation/tank thickness is ignored at this time. Insulation meaning SOFI and not MLI. MLI + Dewars do work together.

**Comment by Starwaster** [comment]
Also, two new RFSettings fields
RFSettings.QvCoefficient which sets the MLI convective coefficient for when tanks are in an atmosphere. (not as effective insulation as in a vacuum)
AnalyticInsulationMultiplier which adjusts how effective MLI is during analytic mode. 

I implemented these so that we can experiment with them without having to recompile the source. The MLI convection coefficient frankly should probably be calculated based on the planet the field is on rather than being a static coefficient. The original equations had outrageously high values that (as I understand it) were based on the presence of 100% nitrogen purge gas and the coefficient was 14600 which resulted in insulation conductivity that was much higher than without insulation. I went with a static value of 3.65 based on what provided some benefit in atmo without being overpowered or overpowering.

The analytic multiplier changes how fast the tank's internal temperature changes during analytic. I'm still not sure what a good value is there. 0.001 is probably too low but higher values result tank internal changing too fast AND resulting in temperatures that are too high when in analytic. So some experimentation is needed here but I couldn't justify holding things up. Currently set to 0.001 so players dont get murdered during analytic

**Comment by Starwaster** [comment]
Updated Cryogenic and BalloonCryo to have MLI (this replaces the older system so I also lowered the baseMass to match Default and Balloon as MLI will incur added mass by itself)

**Comment by Starwaster** [comment]
Also pinging @blowfishpro and @NathanKell

**Comment by blowfishpro** [comment]
Sounds good, I can release in the next couple of days

**Comment by Starwaster** [comment]
@blowfishpro  make sure to pull down the latest changes. I pushed a few more to fix a bug and pushed some config changes.
