### ISSUE TITLE
Unfillable tanks in the VAB

### ISSUE THREAD

**Issue by jrbudda** [NathanKell/ModularFuelSystem#208]
Would it be possible to handle tanks with fillable=false differently? Forcing the resources to 0 every tick in the VAB means you can't simulate mass changes or get dV readings from KER and the like. Maybe allow filling the tanks in the VAB and strip out the resources when launching the ship?

More discussion here https://github.com/jrbudda/KerbalEngineer/issues/13

**Comment by blowfishpro** [comment]
I feel like this would create a lot of user confusion when their resources suddenly disappear.

Why are these tanks unfillable to begin with though?

**Comment by jrbudda** [comment]
In this specific instance the tanks are for a resource that can only be harvested off-world. I believe the setting is also used for tanks like life-support-waste which you don't want to launch full.

User confusion can be mitigated on the GUI, I'd think.

**Comment by jrbudda** [comment]
Hang on a second I think i've been misled as to what the problem actually is.
