### ISSUE TITLE
Unmanaged Resource feature discussion

### ISSUE THREAD

**Issue by Starwaster** [NathanKell/ModularFuelSystem#218]
Creating this to have a place to discuss and track an upcoming feature: Unmanaged Resources. Put simply, this is the ability to define in a part config resources that will not be touched by Modular Fuel System or Real Fuels. 

This primarily has life support mods in mind which might (for example) define Oxygen on a command pod which will also likely have ModuleFuelTanks defined on it. Typically we would define a number of TANK nodes with the life support resources so that they will not be deleted by MFS along with other resources. However, they can still be accidentally deleted by the player and there is no way to exempt those resources.

Now it is possible to do that. We can define as part of the ModuleFuelTanks config any number of UNMANAGED_RESOURCE nodes which will define a quantity of a given resource that will exist on the part separate from any tanks that it might have been configured with or that the player might have added. Details to follow but basically, if we define 5000 units of unmanaged Oxygen on a part, then the amount of Oxygen resource will be 5000 _plus any Oxygen the player might have added via MFT_. Attached is a build for KSP 1.3.1 (ignore any version errors)

[RealFuels_for_1.3.1_unmanaged_resources.zip](https://github.com/NathanKell/ModularFuelSystem/files/2815199/RealFuels_for_1.3.1_unmanaged_resources.zip)

**Comment by Starwaster** [comment]
// The UNMANAGED_RESOURCE reserves a portion of a resource that will not be touched by MFS/RF.
// Hence, it is 'unmanaged'. The node is placed inside a ModuleFuelTanks node and should be
// accompanied by the resource itself being placed in the PART. In this example, 5100 units of Oxygen
// are reserved for a Mk2Pod. This will prevent the user from accidentally deleting the Oxygen
// and then accidentally launching without it. This Oxygen could be for a life support mod and might
// represent O2 tanks or cabin air. These 5100 units will always be present even if all Oxygen tanks are
// deleted from the part. If additional Oxygen is installed via the tank GUI then that will be a quantity
// in addition to the original 5100. It will also be there regardless of 
// what tank type the player might switch to. (i.e. ServiceModule, Default, etc)

@PART[Mk2Pod]
{
	RESOURCE
	{
		name = Oxygen
		amount = 5100
		maxAmount = 5100
	}
	MODULE
	{
		name = ModuleFuelTanks
		basemass = -1
		volume = 665
		
		type = ServiceModule

		UNMANAGED_RESOURCE
		{
			name = Oxygen
			amount = 5100
			maxAmount = 5100
		}
	}
}

**Comment by pap1723** [comment]
Great stuff!

**Comment by Starwaster** [comment]
(this was implemented in 6efb3877d7db65c2d436c58a84910051eb7c2b1b)
