### ISSUE TITLE
Engine GUI user friendliness

### ISSUE THREAD

**Issue by ppboyle** [NathanKell/ModularFuelSystem#219]
Right now, afaik, the only way to close that panel is to go to back to the engine you initially opened it on, open its PAW, and close it there.

This doesn't work out so well when you have 8 RCS engines and you've forgotten which one you had opened the GUI from.

It'd be lovely if there was a close button to close the GUI without going through the PAW.

Also nice - being able to open the GUI of a different engine without closing the existing one.  Instead, hitting 'open gui' would replace the existing GUI with the GUI of the engine you just tried to open.

So yeah - I use too many single-nozzle RCS blocks, but I'm sure I'm not the only one.

**Comment by Starwaster** [comment]
Closing as fixed
