### ISSUE TITLE
Cloning a part with the Alt-Key deletes cloned tanks configs

### ISSUE THREAD

**Issue by fat-lobyte** [NathanKell/ModularFuelSystem#224]
Cloning one or multiple parts that have a RealFuels tank config using the Alt-Key in the editor deletes the tank configuration in the cloned subassembly, and the tanks have to be reconfigured.

Strangely, only the tanks along the "center" (all parts that are node-attached directly or indirectly to the root part of the cloned subassembly) are deleted. Tanks of Side attached stacks are not deleted.

Here's a picture that illustrates this:

![tanks-duplicated](https://user-images.githubusercontent.com/173609/59521203-fddaf000-8ecb-11e9-805a-0375da7cdb7e.png)

The top tanks are the originally placed and configured tanks. The bottom tanks are duplicated by holding down the Alt-key. Note that the center tank has lost its Kerosene, while the side tanks still have their LH2.

**Comment by Starwaster** [comment]
Closing this as fixed. I'm not sure which specific commit fixed it. @todi looks like this one maybe? b88cb6b70d694b0a3f28e04212ace6590971d923

At any rate this will be in the next release. (which won't be too far in the future)
