### ISSUE TITLE
Unnecessary TANK spam in savegames

### ISSUE THREAD

**Issue by siimav** [NathanKell/ModularFuelSystem#226]
I counted 59 TANK elements inside each ModuleFuelTanks PartModule in my persistent.sfs wheras only 1-2 of those actually have some fuel inside them. This makes RF one of the worst savegame bloat creators out there.
ModuleFuelTanks should only write those TANK elements to the ConfigNode that have maxAmount > 0. Those could easily be excluded in the FuelTankList.Save() method. I guess those excluded tanks would need to be dynamically reloaded during the OnLoad() but it shouldn't be all that hard. For the flight scene, it would probably even be unnecessary.

**Comment by Starwaster** [comment]
Yeah I've been aware of this for years but I've been reluctant to take action on it given the potential for totally (pardon the vulgarity) fucking people over with unforeseen consequences.

Any fix had better have the shit tested out of it before going live. And that means more than 2-3 people agreeing to download my test build and then never hearing from them again until after the whatever-it-is goes live and screws something up.

**Comment by siimav** [comment]
About modifying tanks in the field - what realistic use case could that serve? This being affected would depend on whether all the TANKs are restored from part prefab on load or not.

**Comment by Starwaster** [comment]
obviously so that you change what resources are stored in the part.

Look, I get that this is a beef for you but aren't there actual REAL bugs that need more attention? If you focus the same zeal on them then maybe we can get some long standing issues closed out.

**Comment by RCrockford** [comment]
Fixed by #248
