### ISSUE TITLE
Broken re-rooting with RealFuels tanks

### ISSUE THREAD

**Issue by SlavDimov** [NathanKell/ModularFuelSystem#228]
I believe the RealFuels tanks are causing the game to freeze, when trying to re-root a craft.
Basically trying to select a part that is radially attached to a RealFuels tank as a root part causes the game to freeze indefinitely.

Steps to reproduce:
1. load the craft file from the attached test.zip
2. try to re-root the craft, by selecting the strut as the root part

Expected behavior:
The root part changes to the strut, just like it does when re-rooting to a radially attached part that is not connected to a real fuels tank.

Actual behavior:
The game freezes indefinitely, with the only solution being to force kill its process.

KSP Version: 1.6.1 Steam

Side note:
I do have other mods installed, like RealismOverhaul and RP-1 (installed by specifically following [these](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.6.1) instructions), however this problem only exists when dealing with RealFuels tanks, which makes me believe the mod alone is responsible for the bug.

Full list of my mods (generated from CKAN), if it is any help:
> RealismOverhaul,
B9-PWings-Fork,
DeadlyReentry,
HangerExtenderExtended,
KSP-AVC,
MechJeb2,
ProceduralFairings,
ProceduralFairings-ForEverything,
ProceduralParts,
RCSBuildAidCont,
RealSolarSystem,
KSCSwitcher,
SemiSaturatableRW,
TACLS,
TestFlight,
TexturesUnlimited,
Toolbar,
RealismOverhaulCraftFiles,
DMagicOrbitalScience,
KAS,
SCANsat,
ATKPropulsionPack,
CryoEngines,
FASA,
FilterExtensions,
NearFutureConstruction,
NearFuturePropulsion,
NearFutureSolar,
NearFutureSpacecraft,
RealScaleBoosters,
AntaresCygnus,
RN-SovietRockets,
RN-SalyutStations,
RN-Skylab,
RN-SovietProbes,
RN-USProbesPack,
RN-USRockets,
SXTContinued,
Taerobee,
NewTantares,
RSSTextures2048,
AdvancedJetEngine,
FerramAerospaceResearchContinued,
ModuleManager,
ModularFlightIntegrator,
SolverEngines,
KerbalJointReinforcementContinued,
RealChute,
RealFuels,
CommunityResourcePack,
RealHeat,
RealPlume,
SmokeScreen,
ToolbarController,
ClickThroughBlocker,
unBlur,
Kopernicus,
BackgroundResources,
B9PartSwitch,
CryoTanks,
DynamicBatteryStorage,
DeployableEngines,
NearFutureSolar-Core,
NearFutureProps,
BDAnimationModules,
FirespitterCore,
FirespitterResourcesConfig,
RetractableLiftingSurface,
CommunityTerrainTexturePack,
DistantObject,
DistantObject-RealSolarSystem,
TextureReplacer,
MainSailorTextures-Essentials,
kOS,
SpeedUnitAnnex,
RSSDateTimeFormatter,
MainSailorTextures-Complete,
KIS,
KerbalInventorySystemNoFun,
EditorExtensionsRedux,
CommunityPartsTitles,
CommunityCategoryKit,
KSPWheel,
MagiCore,
RasterPropMonitor-Core,
StageRecovery,
TweakScale,
KRASH,
KerbalConstructionTime,
KerbalAlarmClock,
B9AnimationModules,
AirplanePlus,
CustomBarnKit-RO,
PatchManager,
Chatterer,
KerbalGPSRevived,
BluedogDB,
DMagicScienceAnimate,
RP-0,
ScienceAlert,
WaypointManager,
ContractConfigurator,
VenStockRevamp

 
[test.zip](https://github.com/NathanKell/ModularFuelSystem/files/3340936/test.zip)

**Comment by MikeOnTea** [comment]
This has been reported for procedural parts: https://github.com/Tidal-Stream/ProceduralParts/issues/15

Have you tested if this happens with a non procedural parts tank?

**Comment by SlavDimov** [comment]
Yes, I tried with the X-1 propellant tanks from the Taerobee mod. The problem does not occur with them.

**Comment by MikeOnTea** [comment]
So close this bug if it is not RealFuels related?

**Comment by SlavDimov** [comment]
Yes, sorry I forgot. Thanks.
