### ISSUE TITLE
Add close window button to engine/tank  selection window

### ISSUE THREAD

**Issue by zajc3w** [NathanKell/ModularFuelSystem#229]
Engine and tank GUIs need close button, having to go back to last edited engine/tank to close it's window is irritating. If for some reason you don't like having close window buttons, make gui windows close when it's parent part is deselected.

**Comment by Starwaster** [comment]
The next update will have windows that close when the part is deselected.

**Comment by Gordon-Dry** [comment]
You're right, the ROTanks-specific version of RF already does that.

**Comment by zajc3w** [comment]
Awesome, thanks for awesome mod.
