### ISSUE TITLE
Null ref when entering physics range on parts with modulecommand and moduleRCS

### ISSUE THREAD

**Issue by raidernick** [NathanKell/ModularFuelSystem#237]
This has been a long standing issue with(apparently) this mod since 1.4.x and I never bothered to report it because you can fix it by reloading the craft. However you really shouldn't need to be doing that. Any part that has modulercsfx and modulecommand on it, when you move outside it's physics range with another ship and then, get close again will start spamming all of it's rcs ports all the time until you reload the craft(by going to tracking station and back) or save while still inside physics range.

The errors it throws are this: https://pastebin.com/S2u5utAJ

@Starwaster @blowfishpro

**Comment by Starwaster** [comment]
Need your ModuleManager.ConfigCache file and the entire log file

**Comment by Starwaster** [comment]
Also, very strongly leaning towards this being a config issue. I've traced through the code, including KSP code and nothing is going on with Real Fuels other than ModuleEnginesRF and SolverEngines initializing in OnStart(). Then it passes to the stock code and that's where all this is happening and it's happening because it's looking for a GameObject or a transform that doesn't exist. Or because it got nulled out because runningEffectname doesn't exist

**Comment by raidernick** [comment]
@Starwaster I sent you the logs on discord, as for what parts it's happening to, all of my parts, KK parts and FASA parts I maintain that have combined rcs and command modules. I can give you a few example parts of mine:
rn_cygnus, rn_cygnus_e, rn_cassini, galileo_mb

There are many many more parts than that so I'm hoping this is a simple fix that won't require separating the rcs modules from the core parts. I've had to do this on the soyuz and salyut parts already because those are frequently used with docking where you are entering and exiting the physics range. It happens on a lot more things though it's just less noticeable since they are deep space probes that you don't rendezvous with and always switch to in the tracking center which fixes the issue anyway.

**Comment by raidernick** [comment]
I would like to also point out that the twitch streamer tylerraiz was the first one to notice this. I wouldn't have even known about the issue had he not told me about it. So it can at least be replicated by someone other than me. He is on the RO discord if you need to talk to him I'm not sure he has a git account.

**Comment by Starwaster** [comment]
Yup. Not a Real Fuels issue. This same thing can happen in stock if ModuleRCSFX or ModuleEnginesFX (which ModuleEngineRF is a child of) are missing runningEffectName. That is an absolute must. The stock code assumes that field has a value and probably also assume that it refers to a valid effect. 

Take rn_cygnus for example
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/RaiderNick/RO_RN_Cygnus.cfg

It is being converted from ModuleRCS to ModuleRCSFX but runningEffectName was not added And  again it has to point to a valid effect - typically the effect used is named running. All four of the parts have that effect so you just need to add the missing field.

(you will find that those parts have both ModuleRCSFX and ModuleEnginesRF and that runningEffectName may be present on one module but not the other)

Closing this out as it's an RO configuration issue.

**Comment by raidernick** [comment]
@Starwaster you only checked that one part. It's definitely not related to runningEffectName being missing at all. Check galileo_mb, in this RO config it just modifies the stock rcs rather than replacing it like the cygnus one.
https://github.com/KSP-RO/RealismOverhaul/blob/53d8e159f6f258f1ee3aacd8918d0867ec13f2bf/GameData/RealismOverhaul/RO_SuggestedMods/RaiderNick/US_Probes_Galileo.cfg#L63

If you look into the stock config that it is modifying it has runningEffectName defined and it is not being removed or changed by the RO config and is still there in the mm configcache I sent you, so it can't be related to that missing.

https://github.com/KSP-RO/USProbesPack/blob/d82b8da90f17198f24cd77d264955495ed81f86e/GameData/RN_US_Probes/Galileo/galileo_mb.cfg#L175
