### ISSUE TITLE
Fuel pump code disabled on non-stock pads

### ISSUE THREAD

**Issue by ryanc55** [NathanKell/ModularFuelSystem#243]
In RealFuels.SetupGUI() the check for enablePump is currently:   if (vessel != null && vessel.LandedInKSC)
This is false for non-stock pads such as those placed by Kerbal Konstructs and therefore those pads are not  keeping boiloff from happening.   Some tanks can heat up enough when held on the pad for a long time to explode on ascent.

Perhaps:  if (vessel != null && vessel.situation == Vessel.Situations.PRELAUNCH)  ?

**Comment by Starwaster** [comment]
Sounds like a reasonable change.

I'll take a look at it. You're sure that vessel situation doesn't stray from PRELAUNCH for that pad?

(not that I think the current implementation is correct, but it should at least be consistent)

**Comment by ryanc55** [comment]
Yes, I've been playing with that change for a a dozen or so launches now and it seems to work as expected.
