### ISSUE TITLE
InvalidOperationException spam (at RealFuels.Utilities.get_KerbalismFound & RealFuels.Tanks..CalculateTankBoiloff)

### ISSUE THREAD

**Issue by fluff-y** [NathanKell/ModularFuelSystem#260]
As soon as i launch or load a vessel with LH2 in his Tanks, i get the exception spam.

I'm suspecting it might have to do with kerbalism integration, which i do not have installed, but i could be very wrong.

[ModuleManager.ConfigCache.txt](https://github.com/NathanKell/ModularFuelSystem/files/6317240/ModuleManager.ConfigCache.txt)
[Player.log](https://github.com/NathanKell/ModularFuelSystem/files/6317287/Player.log)

Player.log Spam:

> InvalidOperationException: Nullable object must have a value.
  at System.Nullable`1[T].get_Value () [0x00008] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at RealFuels.Utilities.get_KerbalismFound () [0x00066] in <44cbc38b12b847cea2c65f0e6b0f937a>:0 
  at RealFuels.Tanks.ModuleFuelTanks.CalculateTankBoiloff (System.Double deltaTime, System.Boolean analyticalMode, System.Double unclampedIntScalar, System.Double unclampedSkinScalar) [0x0035c] in <44cbc38b12b847cea2c65f0e6b0f937a>:0 
  at RealFuels.Tanks.ModuleFuelTanks.FixedUpdate () [0x00029] in <44cbc38b12b847cea2c65f0e6b0f937a>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

edit:
KSP 1.10.1
Real Fuels rf-v12.9.0.1

**Comment by fluff-y** [comment]
Update:

Using LqdOxygen or LqdMethane leads to the same behavior, Nitrogen, NTO & Syntin were save.
It might only effect those with a defined boiloff Product.

The exceptions seem to only occur, when one of the problematic propellant is stored in a service module tank. 
(Tested with both TANK_DEFINITIONs "SM-IV" & "ServiceModule")
The Ballon-, Intergral- & Conventional tanks are unproblematic.

**Comment by DRVeyl** [comment]
Thankyou.  Will get this fixed and a new release out.  Yes, it has to do with the Kerbalism integration... specifically failing when you _don't_ have Kerbalism installed, and also tied to when there are fuels that boil off involved.  Has some other unpleasant side effects besides the NRE spam.

**Comment by DRVeyl** [comment]
Fixed in <https://github.com/NathanKell/ModularFuelSystem/commit/cc55962b1b1478e502e51ad669881c8e39b05536>  (Thanks, Standecco!)
