### ISSUE TITLE
B9PartSwitch integration doesn't work?

### ISSUE THREAD

**Issue by Bellabong** [NathanKell/ModularFuelSystem#267]
So according to #259 I understood that I just have to add b9psModuleID = engineswitch to Moduleengineconfigs and then add b9psSubtypeName =  to each engine config like 

```
MODULE
{
	name = ModuleEngineConfigs
	b9psModuleID = engineSwitch
	
	CONFIG
			{
				b9psSubtypeName = A
			}
	CONFIG
			{
				b9psSubtypeName = B
			}
)
```

However doing that does absolutely nothing, I tried this on BDB's Agena and Redstone engines and thinking there must be something getting in the way I reverted to a very basic install and added some dummy partswitch subtypes to the Reliant and the result is literally nothing happens. The B9 menu is still there and whatever engine config is selected the B9 partswitch is unaffected. 

What am I doing wrong?

**Comment by al2me6** [comment]
We introduced a new, more flexible syntax before release, which is explained here: https://github.com/NathanKell/ModularFuelSystem/pull/263. You can also find existing configs here for reference: https://github.com/KSP-RO/ROEngines/commit/03b556e856c7bd6b49ab9e5ace0b6f24b2c8e3ac.

Let me know if it still doesn't work.

**Comment by Bellabong** [comment]
It works hallelujah! This pretty much solves most of the compatibility issues between BDB and RealFuels, thank you so much btw for implementing this.

**Comment by al2me6** [comment]
Glad to hear that it's useful! 🙂
