### ISSUE TITLE
B9Partswitch integration doesn't fill the tanks

### ISSUE THREAD

**Issue by Bellabong** [NathanKell/ModularFuelSystem#268]
BDB has SRB's which can have variable amounts of fuel (their Altair uses B9Partswitch to switch between Altair I-Star-20 for example, and the Castor 1&2 are handled similarly as well as many others)

Now since B9Partswitch can't update the volume of modulefueltanks [(yet?)](https://github.com/blowfishpro/B9PartSwitch/pull/183) I let it handle the resource amounts on its own, only patching the name of the resource and scaling up the volumeadded and this worked standalone.

However when the B9partswitching is handled by Realfuels it seems to "forget" to fill the tanks upon launch. There's also some bugs in the editor with the lead engine of engines in symmetry showing both sets of fuels, but that might be errors related to B9Partswitch and don't seem of consequence as the vehicle spawns with the correct resource tanks... just empty. This only happens when RF handles that aspect of B9Partswitch and this error appears upon load:  https://pastebin.com/JBiyVAAB

attached is the full log.
[KSP.log](https://github.com/NathanKell/ModularFuelSystem/files/6772779/KSP.log)

**Comment by al2me6** [comment]
Hmm ok, I'll take a look. I suspect it has to do with how I'm calling B9PS.

Can you send me the configs you're working on so I have something to test?

**Comment by Bellabong** [comment]
[RealFuels-Stock.zip](https://github.com/NathanKell/ModularFuelSystem/files/6773004/RealFuels-Stock.zip)
Yeah sure, here's the full set of configs, BDB + Realfuels and their dependencies required. 

The relevant configs are RealFuels-Stock\Bluedog_DB\RF_BDB_Uppersolids,cfg (Altair and the Star 37's) and RF_BDB_Castors.cfg, the first config is for the Castor 1/2.

**Comment by al2me6** [comment]
FWIW, I still see the "failed to add resource" errors even when the switcher is not managed by RF (this was on the Castor 1/2), but the PSPC does indeed get filled.

It's not immediately clear to me why this would have different behavior when managed by RF.

**Comment by al2me6** [comment]
Apologies; it's fixed now. Fuel switching was admittedly not a use-case I had in mind, and thus I didn't consider its implications.

The bug was caused by (unnecessarily) calling B9PS to switch subtypes _in the flight scene_, which causes it to empty all existing resources if resource switching is involved. This has been resolved by respecting B9PS's `switchInFlight` flag.
