### ISSUE TITLE
Independent Throttle does not engage while Main Throttle control is set to 0

### ISSUE THREAD

**Issue by RocketPhoenix** [NathanKell/ModularFuelSystem#269]
An engine with an independent throttle setting does not engage unless the main throttle is above 0%. In vanilla this is not the case.

**To recreate this bug:** On an install including Real Fuels v13.2.0, first turn on 'Advanced Tweakables; in the settings menu. Build a simple rocket with a fuel tank and engine attached to a launch clamp. Right-click on the engine and set 'Throttle' to 'Independent'. Set the throttle amount to 100% for the engine and set the main throttle control on the navball to 0%. With the engine menu still open, activate the engine manually and observe the 'Current Throttle' value as you throttle up the main control just a tap, and then back down to 0%.

(Tested in vanilla, the RP-1 modpack, and a separate install for Real Fuels using RealFuels-Stock v5.1.0 and prerequisites. The bug is present on both modded installs.)

**Comment by NathanKell** [comment]
Yeah, I just use the vessel main throttle. Looks like RF was never fixed while I was gone after independent throttle was added to stock. I'll get that sorted out this weekend. Cheers!
