### ISSUE TITLE
boiloff yield WaitForFixedUpdated should be reinstated

### ISSUE THREAD

**Issue by Starwaster** [NathanKell/ModularFuelSystem#270]
Recent changes made to the boiloff code included removal of 'yield WaitForFixedUpdate'

That change should be reverted.

Boiloff code needs to run last. That was done to ensure that boiloff calculations are done _**AFTER**_ cooling solutions such as radiators happen. There is no benefit to removing the yield. There's no 'answer' to be gotten as that code returns no values.

**Comment by NathanKell** [comment]
I'm not sure I follow. Under integration, well, it's integration--every thermal-involved system needs to use the frame's start temperature, apply its fluxes, and the integrator will figure out the resultant temperature at the end of the frame by looking at fluxes. That's like saying "this engine needs to run after that engine, so when it applies force it applies force _after_ this other engine consumes propellant and lowers the craft mass". Unless I'm very much misunderstanding.

And under (high) warp, well, then we're not integrating at all, we're in analytic.

**Comment by Starwaster** [comment]
Integration is irrelevant except in that certain part fields get cleared. Then FixedUpdate happens. In the radiators, internal flux is applied and then boiloff looks at that to see if cooling is happening. If that happens before radiator FixedUpdate happens then it can’t apply that extra cooling.

**Comment by Starwaster** [comment]
WaitForFixedUpdate was about ENSURING that the boiloff functions can't happen until radiators have had a chance to to run. None of it is about the integrated thermal except as mentioned above.

**Comment by NathanKell** [comment]
But boiloff is a thermal process, i.e. it takes temperature as input, does stuff according to temperature, and then outputs a flux (<= 0 watts). That makes it no different from any other thermal process, and in particular should not make it subject to special treatment. Again, running boiloff after the rest of thermal integration runs is like saying "ok all other engines apply acceleration and draw fuel based on the vessel's stats at the start of the frame, but _this_ special engine applies acceleration based on the vessel mass after it was lowered by the other engines using fuel". Does not make any sense to me, and breaks a bunch of assumptions around how Euler integration works.

Is there something special to do with radiators I'm not getting?

**Comment by Starwaster** [comment]
It's already running after integration. It always has been. You haven't changed that, you've only changed its order with respect to radiators. 

And I'm done here. This isn't going anywhere and to be honest I didn't expect that it would. I just raised the issue because I would have felt worse than if I hadn't.
