### ISSUE TITLE
Can you please add more solid propellants for the Procedural parts solid motor config?

### ISSUE THREAD

**Issue by harrytherocketeer** [NathanKell/ModularFuelSystem#282]
Leaving this here because apparently the RO github site doesnt allow for any more issues somehow.

**Comment by NathanKell** [comment]
I don't even know what you're asking, but it doesn't sound at all related to RF.

**Comment by harrytherocketeer** [comment]
Well, the procedural SRB only has one fuel choice - SolidFuel. I want real life solid propellants added to the procedural srb.
