### ISSUE TITLE
RealFuels makes ModuleEngines.flameout flag wrong because of residuals.

### ISSUE THREAD

**Issue by Dunbaratu** [NathanKell/ModularFuelSystem#292]
RealFuels causes this stock flag to not tell the truth anymore.  With Realfuels installed, just because ModuleEngines.flameout is false that doesn't actually mean the engine isn't flamed out.  This causes problems for kOS scripts, which have access to reading that flag and can use it to make staging decisions.

``ModuleEngines.flameout`` flag is supposed to represent whether the engine has been flamed out due to fuel starvation.  If it's true, then it no longer has fuel it could use if it was re-ignited.  If it is false then it has usable fuel left.  But with RealFuels making it possible for an engine to flame out with a little residual fuel left, that flag is no longer correct.  (Stock does not realize the residual fuel is unusable, so it does not realize the engine is fuel starved and doesn't set the flag.)

If Realfuels causes the engine to flameout even though there's a little fuel still left, it should also be setting that flag to let the rest of the mods out there know the engine is flamed out.

[EDIT: After implementing this change it would be a good idea to check that the game is still turning the flag back OFF properly when it's supposed to.  In stock, when an engine's ``flameout`` flag gets turned on, it gets turned back off again when the engine gets ignited again.  (Which is possible if the engine gets access to some more fuel via fuel transfers or changing some part's crossfeed setting.)]

**Comment by DRVeyl** [comment]
@NathanKell 
Should this be fixed here [perhaps in MERF.UpdateSolver near <https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Engines/ModuleEnginesRF.cs#L724>] or should this be fixed in SolverEngines when, after calling UpdatePropellant <https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Engines/ModuleEnginesRF.cs#L985> the result is false?

**Comment by NathanKell** [comment]
This is pretty weird because, as the first link you gave shows, we *do* flamout the other engines, and I had thought that the first engine to exhaust also entered a flamed-out state.

**Comment by NathanKell** [comment]
Ok, this is super weird. Solver *should* already be handling this case. Not really seeing how it's not, will dig.

**Comment by NathanKell** [comment]
And so it is. Can't repro. Launched a WAC Corporal and attaching a guiactive field to the `flameout` bool and it behaves as expected. What's the repro where it doesn't, @Dunbaratu ?

**Comment by NathanKell** [comment]
OH I see the problem. It's once you throttle back to zero and the engine goes unignited, we Unflameout() regardless of propellant state.
