### ISSUE TITLE
MissingMethodException when trying to unlock new avionics

### ISSUE THREAD

**Issue by Codelet** [NathanKell/ModularFuelSystem#296]
Version 15.2.1
When trying to unlock new tier of avionics from UI in VAB nothing happens and console gives me MissingMethodException: bool RealFuels.EntryCostManager.PurchaseConfig(string)
Apparently this method signature was changed to have two parameters by [this commit](https://github.com/NathanKell/ModularFuelSystem/commit/cd0e48b34e43611d34a85784e7d74c343862b656)
If I understand correct there is still somewhere a binding for button click which looks for old signature using reflection.
Can this be fixed ASAP as it is not possible to unlock any avionics and thus progress through the game. Or maybe there is some workaround?

Best Regards.

![image](https://user-images.githubusercontent.com/26896486/183909623-41dd4281-f1e4-46cc-ab79-da8d7958d3a2.png)

**Comment by Codelet** [comment]
I downgraded just RealFuels addon to 15.1.0 and it seems to work, I hope using latest RP-1 express install with RealFuels downgraded will not introduce other issues which are not visible immediately :)

**Comment by NathanKell** [comment]
Fixed in v15.2.2.

**Comment by Codelet** [comment]
Double checked with 15.2.2 installed and it is working idd.
Thanks a lot for what you are doing!
