### ISSUE TITLE
'Go back to preset'/Defaults button in Tank GUI

### ISSUE THREAD

**Issue by Taverius** [NathanKell/ModularFuelSystem#34]
A way to go back to a tank_def or part override defined values, for tanks that don't have multiple types defined.

**Comment by Starwaster** [comment]
#218 - 6efb3877d7db65c2d436c58a84910051eb7c2b1b might address part of this issue as it allows for the configuration of resources on a part that will not be touched by MFS/RF under any circumstances.

**Comment by DRVeyl** [comment]
Closed as no longer necessary.  (Auto-fill features basically cover this.)
