### ISSUE TITLE
Uranium

### ISSUE THREAD

**Issue by eggrobin** [NathanKell/ModularFuelSystem#58]
The name `DepU235Rods` is extremely misleading, and `U235Rods` is mostly misleading, as discussed on IRC.
They are used in RO to model reactor fuel rods and (spent and new), and the spent stuff [*is not*](http://en.wikipedia.org/wiki/Spent_nuclear_fuel#Nature_of_spent_fuel) depleted uranium: it contains plutonium, a right mess of actinides, and it is typically still *more enriched* than naturally-occuring uranium.
Change to `SpentUraniumRods` respectively `UraniumRods`, (we probably don't want to go too far into the specifics of the kind of fuel yet: while UO<sub>2</sub> is frequent, SNAP-10A used UZrH).

**Comment by Starwaster** [comment]
Closing this as outdated plus Real Fuels doesn't maintain its own resource list since switching to CRP.
