### ISSUE TITLE
TAC LS Support.

### ISSUE THREAD

**Issue by Climberfx** [NathanKell/ModularFuelSystem#63]
In the present, i need to remove Modular Fuel Tanks because it mess with the cockpit and crew LS tanks.  (Stock, B9, ALCOR). Removing everyone of then, letting me with no life support at all.
I think this need a fix, to regain compatibility.

**Comment by NathanKell** [comment]
I believe MFT and TACLS are fixed for this. If not please reopen.

**Comment by Climberfx** [comment]
Great :) Many many thanks Nathan!
