### ISSUE TITLE
Make engine CONFIGs cost to unlock

### ISSUE THREAD

**Issue by NathanKell** [NathanKell/ModularFuelSystem#79]
Science? Funds? Foozballs?

**Comment by BevoLJ** [comment]
Obviously snacks!  

But this I would love to see, if it is possible.  I think the cost should probably come from funds.  I tend to prefer the cost of things coming from funding as it can somewhat simulate funding science/research too. Science itself to me seems far harder to balance out as so players may enjoy playing with mods like DMagic's (like I do), while others may not use those mods and so won't get as much science from missions.

**Comment by ImAHungryMan** [comment]
By engine configs are we talking about the ability to use different propellants?

If so, I would prefer a science cost actually. If it was integrated into the tech tree similar to the way Procedural Fairings does it, then balance shouldn't be too much of an issue.

**Comment by Ialdabaoth** [comment]
Correct - science cost to unlock configs seems obviously correct.

I'd suggest two values - a science cost multiplier to unlock a config (as a
percentage of the engine's base cost) and a science cost multiplier to
unlock each subsequent tech level within that config.

**Comment by NathanKell** [comment]
Ah, yes, the multi-use nature of RF.

Sounds like the best policy will be to allow both science and funds entryCosts for configs and for TLs. as @Ialdabaoth suggests these should be multipliers, though the question then becomes, multipliers of what? (obvious choices are part cost, part entryCost, or CONFIG cost).
