### ISSUE TITLE
TweakScale interaction

### ISSUE THREAD

**Issue by pellinor0** [NathanKell/ModularFuelSystem#84]
I noticed that MFT places a dll into the TweakScale folder. This file is prone to vanishing when someone deletes the TweakScale folder to do a clean update of the mod. It would be more robust to place the dll with MFT. 

Maybe you can even do without an extra dll, I had a report from someone who probably lost the dll and wrote a config instead:
http://forum.kerbalspaceprogram.com/threads/110899-WIP-TweakScale-Development-Thread?p=1782006&viewfull=1#post1782006

I'm also confused that TweakScale includes a config for realFuels but not for MFT. Shouldn't both mods need the same treatment? 

TWEAKSCALEEXPONENTS
{
    name = RealFuels.ModuleFuelTanks
    
    basemass = 3
    basemassPV = 3
	totalVolume = 3
	volume = 3
	fuelList
	{
		amount = 3
		maxAmount = 3
	}
}

**Comment by NathanKell** [comment]
@pellinor0  Tweakscale should not include scaleexponents for either RF or MFT, instead it should include the ignore config that I added way back when so it doesn't touch resources if the MFT module is present. The interaction dll is the appropriate approach; directly changing those values cause bad things to happen.
RF now redistributes Scale_Redist and thus ships its interaction dll in its own folder; my understanding is @taniwha-qf will do the same for next MFT.

**Comment by NathanKell** [comment]
Ah, found my old pull. https://github.com/Biotronic/TweakScale/pull/10

**Comment by pellinor0** [comment]
The ignore line still exists, as I understand it will ignore both MFT and RF modules. 

So I'll remove the scale exponents for RealFuels.ModuleFuelTanks for the next TweakScale version.

**Comment by NathanKell** [comment]
Thanks!

**Comment by NathanKell** [comment]
As I presume this is dealt with, I'm closing it.  @pellinor0  let me know if you want it open again.
