### ISSUE TITLE
Engines do not re ignite after 0% throttle

### ISSUE THREAD

**Issue by svm420** [NathanKell/ModularFuelSystem#88]
Issue is when an engine is taken to 0 throttle and then increased above 0 the engine remains off and can only be re ignited by shutting the engine down in the Rclick menu setting throttle above 0. Finally quicksave and quickload, and activate the engines again and they re ignite. If throttle is not set above 0, or engines aren't actually shut down the method fails. This is with the latest solver engines dll

**Comment by NathanKell** [comment]
This is fixed? Was it for MFT or RF?

**Comment by svm420** [comment]
RealFuels and yes latest update to bring it up to date with solver engines fixed it. Thanks for the update :)

**Comment by NathanKell** [comment]
Awesome! Always happy to fix bugs while not realizing I am. :D
