### ISSUE TITLE
Bug. Why pressure-fed hypergolic engines need ullage kicks?

### ISSUE THREAD

**Issue by prollejazz** [NathanKell/ModularFuelSystem#90]
At the moment, 1.0.4, all hypergolic engines seem to need ullage kicks, though the engines are hypergolic on pressurized tanks.

**Comment by NathanKell** [comment]
Please see the about fifty million times I've addressed that this week on the forums. :) (It's the myth that won't die!)

**Comment by mobarre** [comment]
Maybe... Maybe people are not interested in reading the 260 pages of the realfuel threadnaught... That comment is actually valid for every single Kerbal mod out there.
Forums are the worst kind of tool for this (and many other) jobs. If you've already adressed the issue a million times, then maybe an FAQ on a wiki somewhere would save you some time ? :)

**Comment by Starwaster** [comment]
People will then claim that they don't have time to read the FAQ/Wiki or claim that they didn't know it was there. (because, didn't read the first post because they don't have time to read 260 pages of the Real Fuel thread)

**Comment by mobarre** [comment]
Well, that makes sense too :)
