### ISSUE TITLE
Calling "ModuleEngineConfigs.ChangeEngineType" causes KSP to CTD

### ISSUE THREAD

**Issue by ItMustBeACamel** [NathanKell/ModularFuelSystem#91]
ProceduralParts ProceduralSRB module uses this function via reflection. Seems like there is something odd going on. Maybe a stack overrun? RF recently had some major changes right? (ullaging?) Is there something I need to take notice of/change from a PP perspective?

**Comment by NathanKell** [comment]
@ItMustBeACamel  must be the KSPAPIExtension PartMessage call, since that's the only relevant thing changed. Guess I'll just use SendMessage instead.

**Comment by NathanKell** [comment]
Fixed in 34e5474c350c27a459404c07caa6be7d3865b83f and in release v10.4.6
