### ISSUE TITLE
Real plume incompatibility

### ISSUE THREAD

**Issue by cvanweelden** [NathanKell/ModularFuelSystem#98]
When I install real plume with stock configs after installing real fuels with stockalike configs, the engine ignitor features disappear (it will let me ignite engines infinitely under all conditions). It doesn't show the fuel state or the ignitions remaining.

Reproduces always. Tested with Swivel and Reliant engines.
1. On a clean install with CKAN install real fuels (rf-v 10.5), select stockalike configs (v2.1.8).
2. With CKAN install real  plume (1:v10.4.6), select stock configs (v0.4).

This also installed (as dependencies):
- Community Resource Pack (0.4.4)
- Module Manager (2.6.6)
- ModuleRCSFX (v4.1)
- SmokeScreen (2.6.7)
- Solver engines plugin (v1.9)

P.S. Love this mod!

**Comment by cvanweelden** [comment]
Can confirm it doesn't happen with just SmokeScreen, or with SmokeScreen + HotRockets.

**Comment by Raptor831** [comment]
This is due to the fact that Real Plume - Stock changes all of the engine modules to ModuleEnginesFX, which has none of the goodies associated with Real Fuels. You can fix this by:

* Change any reference in Real Plume - Stock configs of ModuleEngineFX with ModuleEngineRF, or
* Write up a MM config to change any ModuleEngineFX node to ModuleEngineRF

Second one is probably preferable, since you're not messing with another mod's files, but either will work.

**Comment by Felger** [comment]
Yeah, I probably need to build that patch in.  I need to come up with a good way to handle that across all the configs.

**Comment by Raptor831** [comment]
I was thinking simply a MM patch applied only if RealFuels is installed. Say:

```
@PART[*]:HAS[@MODULE[ModuleEnginesFX],@PLUME[*]]:NEEDS[RealFuels]:AFTER[zRealPlume]
{
  @MODULE[ModuleEnginesFX],*
  {
    @name = ModuleEnginesRF
  }
}
```

In RF Stockalike, the only reason it's an issue is because Real Plume runs after Stockalike. So running this during the :AFTER[zRealPlume] pass will ensure that ModuleEnginesRF will get used.

**Comment by NathanKell** [comment]
Instead of a blanket,  tag what is rf when real plume does its pass and
then do a final has pass on that tag to change back.
Unless the desired  behavior is indeed to change everything over. The only
thing rf module does differently by default is the different thermal
behavior.

Sent by my thumbs, slowly.

**Comment by Raptor831** [comment]
That was the intent of my patch, though @NathanKell has probably the more elegant solution.

**Comment by NathanKell** [comment]
Yeah, but yours could hit engines that RP configures but RF doesn't. Like I said above, that might be desirable (you get the neat features of ModuleEnginesRF, like a discreet chamber temp as apart from internal part temp and skin temp) or it might not (for the same reason). The tagging approach will only restore, not force. :)

**Comment by Raptor831** [comment]
Agreed. :-) Tagging and going back is definitely a better way.

**Comment by NathanKell** [comment]
@Raptor831  @Felger did this ever get sorted?

**Comment by Raptor831** [comment]
Haven't yet on my end, but as you can see above, I've added it to my list.

**Comment by Felger** [comment]
I completely forgot about this.  Easy enough to fix in a post-patch on my end though.

**Comment by Raptor831** [comment]
@Felger @NathanKell Ok, what would be the best way to "tag" configs on my end?

**Comment by Felger** [comment]
I'm thinking something along the lines of:

````
@PART[*]:HAS[@MODULE[ModuleEnginesRF]:BEFORE[RealPlume]
{
   @MODULE[ModuleEnginesRF]
   {
      %RFConfig = TRUE
   }
}

@PART[*]:HAS[@MODULE[ModuleEngines*]:HAS[RFConfig[TRUE]]]:FINAL
{
   @MODULE[ModuleEngines*],*
   {
      @name = ModuleEnginesRF
   }
}
````

Hopefully I got my MM syntax correct.  I'll also need to make sure my patches are all applied in or after RealPlume.

**Comment by Raptor831** [comment]
I was thinking, I could apply the `RFConfig = TRUE` on my end, within the actual RF configs. Which means explicitly that the tag has only been applied to engines I've changed. Then you can run the swap and we can be reasonably sure that only the RF configs are changed.

Could be just as easy to MM it like the above, though. I tend to make things more complicated than they need to be! :-)

**Comment by NathanKell** [comment]
IMO @Felger's is better since it will work for any engine pack, and it doesn't rely on an engine pack author realizing there will be a conflict and preparing for it. Let the thing doing the clobbering do the unclobbering. :)

**Comment by NathanKell** [comment]
Ah, except @Felger you want
@MODULE[ModuleEngines*],*:HAS[#RFConfig[TRUE]]

so it doesn't disturb engine modules that don't have it.

**Comment by Raptor831** [comment]
@NathanKell Sounds good to me. Clobber away. :)

**Comment by Felger** [comment]
RealPlume-Stock v0.8 (Should) fix this issue.  Let me know if it doesn't work.

**Comment by NathanKell** [comment]
\o/ Just saw someone mention getting it still, presumably before 8, so good to hear! :)

**Comment by LebedevRI** [comment]
@Felger i have RealPlume-Stock v0.8.1, and it still happens.

**Comment by Felger** [comment]
https://github.com/KSP-RO/RealPlume-StockConfigs/blob/master/GameData/RealPlume-Stock/Compatibility.cfg

Make sure you have that file.  If not, can you toss up a pastebin of the ModuleManager.ConfigCache of  a part that's showing the funky behavior?

**Comment by LebedevRI** [comment]
@Felger https://paste.debian.net/315808/

`KSP_linux/GameData/RealPlume/RealPlume-Stock/Compatibility.cfg`:
```
@PART[*]:HAS[@MODULE[ModuleEnginesRF]]:BEFORE[RealPlume]
{
   @MODULE[ModuleEnginesRF]
   {
      %RFConfig = TRUE
   }
}

@PART[*]:HAS[@MODULE[ModuleEngines*]:HAS[RFConfig[TRUE]]]:FINAL
{
   @MODULE[ModuleEngines*],*:HAS[#RFConfig[TRUE]]
   {
      @name = ModuleEnginesRF
   }
}
```

**Comment by Felger** [comment]
Oh, I might be a dummy.  Change the @PART line in the second block to:

`
@PART[*]:HAS[@MODULE[ModuleEngines*]:HAS[#RFConfig[TRUE]]]:FINAL
`

See if that fixes it.

**Comment by LebedevRI** [comment]
@Felger 
`KSP_linux/GameData/RealPlume/RealPlume-Stock/Compatibility.cfg`:
```
@PART[*]:HAS[@MODULE[ModuleEnginesRF]]:BEFORE[RealPlume]
{
   @MODULE[ModuleEnginesRF]
   {
      %RFConfig = TRUE
   }
}

@PART[*]:HAS[@MODULE[ModuleEngines*]:HAS[#RFConfig[TRUE]]]:FINAL
{
   @MODULE[ModuleEngines*],*:HAS[#RFConfig[TRUE]]
   {
      @name = ModuleEnginesRF
   }
}
```
New relevant part of `ModuleManager.ConfigCache`:
https://paste.debian.net/315811/

Now, most of the engines do show Ignitions count in KSP, so i guess it helped.

(Mostly, all SpaceY engines still does not show Ignition count, and still show up in "Filter by Module" -> "Engine", and not in "Filter by Module" -> "Engine (RealFuels)" or "Filter by Module" -> "Engine Configs")

**Comment by Felger** [comment]
When do those configs run? My compatibility patch runs BEFORE[realplume]
and then again in FINAL (bad form, will change to after[zzrealplume] at
some point) to unclobber.

**Comment by LebedevRI** [comment]
@Felger sorry, i'm not exaclty sure what are you asking :(
Here is the part of `ModuleManager.ConfigCache`, with only one of the SpaceY engines with no ullage/ignitions limit: https://paste.debian.net/315865/
(If you prefer more real-time replies, i'm in e.g. IRC #RO channel)

**Comment by Raptor831** [comment]
@LebedevRI I'm not 100% sure the SpaceY engines all have their ignitions set. That mod tends to need some custom love from Stockalike, which also means they don't get updated as rapidly.

**Comment by Felger** [comment]
Okay, so, the SpaceY engines are originally configured as ModuleEngines, which means they likely weren't updated when RealFuels moved to ModuleEnginesRF.  In any case, it's a fairly simple fix, but it needs to be done on the RealFuels config side of things.  RealPlume only unclobbers ModuleEnginesRF, it won't work with any engine modules other than RF or FX. (or any other custom engine modules mirrored from FX).

On IRC, unfortunately my work schedule has somewhat precluded much IRC time recently.  Tagging me on Github is fairly effective though, as I get an email telling me to quit slackin'.

**Comment by speedwaystar** [comment]
the current release of compatibility.cfg still has 

`@PART[*]:HAS[@MODULE[ModuleEngines*]:HAS[RFConfig[TRUE]]]:FINAL`

instead of 

`@PART[*]:HAS[@MODULE[ModuleEngines*]:HAS[#RFConfig[TRUE]]]:FINAL`
